# workflow name
name: project-01
# event >> trigger
on: ["push"]

jobs:
  # name
  test-job:
    # OS or platform
    runs-on: ubuntu-latest
    # steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 ./scripts/hello.py 
        